### PR TITLE
Add load balancer for Openstack within terraform

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Add Dockerfile that provides environment for using kubernetes-ansible
from any machine that has Docker installed.

I was not able to find a way to have all the worker nodes automatically added using terraform natively, so there is a small playbook that will generate it based on the number of worker nodes specified. (It is a bit of a hack but it was a close to automated as I could get.)

In my project I have environment specific variable files that contain a value for `total_members` which should match the number found within the terraform-openstack.tf  file.

### CODE REVIEW

**Comment by altvnk** [comment]
Are you creating here an LB for k8s API service to make it accessible from entire world?
Can we then somehow get an IP into ansible variable and pass into cert generation script as Subject Alternative Name to make cert valid? Also it would be useful to write that address into a kubecfg file for kubectl so you can safely get config from master node, place it under `.kube/config` and operate the cluster from your workstation.

**Comment by kenjones-cisco** [comment]
The load balancer is for exposing your services to the outside world. Not kubernetes itself, but the services deployed on kubernetes.

As to the parts about certs, that would be a nice addition. But I will not be able to add that until I'm back from vacation.

**Comment by altvnk** [comment]
Oh, i see. So with this we can create LB for predefined k8s service (https is used as example)?

**Comment by altvnk** [comment]
Just for info - today i played with [Vulcand](https://vulcand.io). Very interesting LB implementation with dynamic configuration from `etcd`.

**Comment by kenjones-cisco** [comment]
That is very cool. I was just looking for a way so that my "app/service" deployed on my kubernetes instance could be available at a specific endpoint. This was the easiest approach I found given my timeline.

**Comment by kenjones-cisco** [comment]
Closing for now, needs to be resynced. And if the need is there then I can resubmit later.

**Pull request closed without merging**
