### PR TITLE
leverage kube for managing pods, services, and rc

### PR DESCRIPTION
**Pull request by kenjones-cisco**

### CODE REVIEW

**Comment by altvnk** [comment]
This is really cool, i like it!

**Comment by altvnk** [comment]
Seems like plugin doesn't checks if manifest is already loaded:

```
TASK: [skydns | Create or update SkyDNS replication controller] ***************
failed: [k8s-master] => {"failed": true}
msg: error running kubectl (/bin/kubectl --api-version=v1 --namespace=kube-system create --filename=/etc/kubernetes/skydns-rc.yaml) command (rc=1): Error from server: error when creating "/etc/kubernetes/skydns-rc.yaml": replicationControllers "kube-dns-v8" already exists
```

**Comment by kenjones-cisco** [comment]
That is strange, because it does check if the resource is already loaded.

if the state requested is present, then it checks for existence, and returns unchanged.
if the state requested is latest, then it checks for existence, if exists it replaces else create.

 In this particular case the check would have looked like

```
kubectl --api-version=v1 --namespace=kube-system get rc kube-dns-v8
```

If that resulted in False (not found) then the create happens.

**Comment by kenjones-cisco** [comment]
Just found the bug which would be specific to replicationControllers. I will submit the PR in just a moment.

**Comment by altvnk** [comment]
Here is manual check:

```
kubectl --api-version=v1 --namespace=kube-system get rc kube-dns-v8
CONTROLLER    CONTAINER(S)   IMAGE(S)                                         SELECTOR                      REPLICAS
kube-dns-v8   etcd           gcr.io/google_containers/etcd:2.0.9              k8s-app=kube-dns,version=v8   1
              kube2sky       gcr.io/google_containers/kube2sky:1.11
              skydns         gcr.io/google_containers/skydns:2015-03-11-001
              healthz        gcr.io/google_containers/exechealthz:1.0
```

Trying to understand how it's happening.

**Comment by kenjones-cisco** [comment]
The bugfix PR explains why but overly  narrow existence check was the root.

**Pull request merged**
