### PR TITLE
Add persistent storage setup for containers (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Provides the setup of glusterfs as volume manager and replication
in order to provide consistent volume access across the cluster for
containers during and between runtimes.

### CODE REVIEW

**Comment by kenjones-cisco** [comment]
Dependent on #15 as glusterfs requires a cluster of nodes on the server side. As such it will currently fail when running as a single master.

Needs improvement to work for a single master setup.

**Comment by altvnk** [comment]
Probably we can start using more that one master instance since k8s components are installing only on first node in masters group. So we can have fully functional etcd and glusterfs cluster.

**Comment by kenjones-cisco** [comment]
Agreed. Since I had already set this one up for my other project (glusterfs only runs on workers there), I  started the PR so we could continue the HA work. Just didn't have time yet to try on more than 1 control host.

**Comment by kenjones-cisco** [comment]
Most of the credit goes to the MI team, as it is nearly the same minus the consul parts. I just tweaked it for Kubernetes.

**Comment by altvnk** [comment]
So you can create separate branch here and then we can make some test deployments. Make sense?

**Comment by altvnk** [comment]
Also we should think how to provide kubernetes service endpoints for gluster nodes.

**Comment by altvnk** [comment]
Well, once we have working glusterfs further configuration is pretty simple: https://github.com/kubernetes/kubernetes/blob/master/examples/glusterfs/README.md

**Comment by kenjones-cisco** [comment]
Seems I don't have permission to create new branch on this project directly.

**Comment by altvnk** [comment]
@PeterLamar Can you please add push rights for @kenjones-cisco

**Comment by peterlamar** [comment]
Done! @altvnk The Country of Ukraine will be sad that you are working on its Independence day! :)

**Comment by altvnk** [comment]
Thank you, Peter!

Only few mails from sofa, so not a big deal )

**Comment by kenjones-cisco** [comment]
The branch has been pushed. If you want, we can close this PR, and move forward with that branch.

**Comment by kenjones-cisco** [comment]
Thanks @PeterLamar

**Comment by altvnk** [comment]
Good idea, let's do that.

**Pull request closed without merging**
